name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build
    - name: Format
      run: |
        VERBOSE=1 make format
        git diff --exit-code
    - name: Lint
      run: VERBOSE=1 make lint CLIPPY_OPTS="-D warnings"
    - name: Run tests
      run: VERBOSE=1 make check
